## Data Encoding

1. Nominal/OHE Encoding
2. Label and Ordinal Encoding
3. Target Guided Ordinal Encoding

### Nominal/OHE Encoding

In [4]:
import numpy as np 
import pandas as pd 
from sklearn.preprocessing import OneHotEncoder

In [5]:
# creating a simple dataframe 
df =pd.DataFrame({
    'color':['red','green','blue','green','blue','red']
})

In [6]:
df

   color
0    red
1  green
2   blue
3  green
4   blue
5    red

In [ ]:
# create a instance of onehotencoder 
encoder = OneHotEncoder()

In [10]:
# perform fit and transform
encoded = encoder.fit_transform(df[['color']]).toarray()
encoded_df = pd.DataFrame(encoded,columns=encoder.get_feature_names_out())

In [11]:
encoded_df

   color_blue  color_green  color_red
0         0.0          0.0        1.0
1         0.0          1.0        0.0
2         1.0          0.0        0.0
3         0.0          1.0        0.0
4         1.0          0.0        0.0
5         0.0          0.0        1.0

In [12]:
## for new data
encoder.transform([['blue']]).toarray()

c:\Users\ACER\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(

array([[1., 0., 0.]])